[{"crop": "Onion", "type1": "sandy", "type2": "clay", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Ginger", "type1": "sandy loam", "type2": "clay loam", "type3": "red loam", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Arhar/Tur", "type1": "clay", "type2": "sandy", "type3": "loamy", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Samai", "type1": "loamy", "type2": "clay", "type3": "sandy loam", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Garlic", "type1": "sandy loam", "type2": "clay", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Bajra", "type1": "sandy", "type2": "black", "type3": "red", "type4": "gravely", "type5": null, "type6": null}, 
 {"crop": "Small millets", "type1": "loamy", "type2": "clay", "type3": "sandy loam", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Castor seed", "type1": "red", "type2": "sandy", "type3": "alluvial", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Lemon", "type1": "loamy", "type2": "sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Cotton(lint)", "type1": "sandy", "type2": "loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Mesta", "type1": "loamy", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Arecanut", "type1": "laterite", "type2": "red", "type3": "alluvial", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Dry chillies", "type1": "black", "type2": "loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Other  Rabi pulses", "type1": "alluvial", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Groundnut", "type1": "loamy", "type2": "clay loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Horse-gram", "type1": "lateritic", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "other fibres", "type1": "alluvial", "type2": "black", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Banana", "type1": "clay", "type2": "alluvial", "type3": "black", "type4": "red", "type5": "sandy", "type6": null}, 
 {"crop": "Other Fresh Fruits", "type1": "sandy", "type2": "loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Jowar", "type1": "loamy", "type2": "sandy", "type3": "clay loamy", "type4": "alluvial", "type5": null, "type6": null}, 
 {"crop": "Other Kharif pulses", "type1": "alluvial", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Korra", "type1": "loamy", "type2": "sandy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Coconut", "type1": "laterite", "type2": "sandy", "type3": "alluvial", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Maize", "type1": "sandy", "type2": "clay loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "other misc. pulses", "type1": "alluvial", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Coriander", "type1": "sandy loam", "type2": "loamy", "type3": "clay", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Moong(Green Gram)", "type1": "black", "type2": "lateritic", "type3": "loamy", "type4": "sandy", "type5": null, "type6": null}, 
 {"crop": "other oilseeds", "type1": "alluvial", "type2": "red sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Ragi", "type1": "loamy", "type2": "sandy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Potato", "type1": "loamy", "type2": "sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Sweet potato", "type1": "sandy", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Turmeric", "type1": "sandy", "type2": "clay loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Soyabean", "type1": "loamy", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Other Vegetables", "type1": "clay", "type2": "alkaline", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Beans & Mutter(Vegetable)", "type1": "sandy loam", "type2": "clay", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Rice", "type1": "alluvial", "type2": "silt", "type3": "loamy", "type4": "gravely", "type5": "alkaline", "type6": "clay"}, 
 {"crop": "Peas  (vegetable)", "type1": "sandy loam", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Sugarcane", "type1": "sandy", "type2": "loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Sunflower", "type1": "alkaline", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Bhindi", "type1": "clay loam", "type2": "sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Tobacco", "type1": "alluvial", "type2": "black", "type3": "loamy", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Brinjal", "type1": "clay loam", "type2": "sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Pome Granet", "type1": "loamy", "type2": "sandy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Gram", "type1": "sandy", "type2": "cotton", "type3": "loamy", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Wheat", "type1": "loamy", "type2": "clay", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Masoor", "type1": "alluvial", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Rapeseed &Mustard", "type1": "sandy", "type2": "loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Sesamum", "type1": "sandy", "type2": "loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Citrus Fruit", "type1": "sandy loam", "type2": "clay loam", "type3": "alluvial", "type4": "lateritic", "type5": null, "type6": null}, 
 {"crop": "Urad", "type1": "sandy", "type2": "clay", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Cucumber", "type1": "sandy", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Grapes", "type1": "sandy loam", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Linseed", "type1": "loamy", "type2": "clay", "type3": "silty clay", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Sannhamp", "type1": "clay", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Safflower", "type1": "loamy", "type2": "silt", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Mango", "type1": "sandy loam", "type2": "sandy", "type3": "lateritic", "type4": "alluvial", "type5": null, "type6": null}, 
 {"crop": "Sapota", "type1": "alluvium", "type2": "sandy loam", "type3": "black", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Orange", "type1": "loamy", "type2": "sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Papaya", "type1": "sandy loam", "type2": "black", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Tapioca", "type1": "laterite", "type2": "sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Pome Fruit", "type1": "sandy", "type2": "loamy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Tomato", "type1": "loamy", "type2": "sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Bottle Gourd", "type1": "sandy loam", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Cabbage", "type1": "sandy", "type2": "clay", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Varagu", "type1": "alluvial", "type2": "loamy", "type3": "sandy", "type4": null, "type5": null, "type6": null}, 
 {"crop": "Cashewnut", "type1": "sandy", "type2": "sandy loam", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Cowpea(Lobia)", "type1": "sandy loam", "type2": "sandy", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Niger seed", "type1": "black", "type2": "laterite", "type3": null, "type4": null, "type5": null, "type6": null}, 
 {"crop": "Dry ginger", "type1": "sandy loam", "type2": null, "type3": null, "type4": null, "type5": null, "type6": null}]